//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liquid.Domain.Properties
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Liquid.Domain.Properties.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The server is busy and cannot perform this operation now. Please try again in a few moments..
        /// </summary>
        public static string DEPENDENCY_TIME_OUT
        {
            get
            {
                return ResourceManager.GetString("DEPENDENCY_TIME_OUT", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not insert the record because the database already there is another one with same id..
        /// </summary>
        public static string DUPLICATED_INSERTION_CONFLICT
        {
            get
            {
                return ResourceManager.GetString("DUPLICATED_INSERTION_CONFLICT", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string INVITESTATUS_ACCEPTED
        {
            get
            {
                return ResourceManager.GetString("INVITESTATUS_ACCEPTED", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email bounced.
        /// </summary>
        public static string INVITESTATUS_BOUNCED
        {
            get
            {
                return ResourceManager.GetString("INVITESTATUS_BOUNCED", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to To be accepted.
        /// </summary>
        public static string INVITESTATUS_PENDING
        {
            get
            {
                return ResourceManager.GetString("INVITESTATUS_PENDING", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove and invite again.
        /// </summary>
        public static string INVITESTATUS_REINVITE
        {
            get
            {
                return ResourceManager.GetString("INVITESTATUS_REINVITE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Malformed or empty parameters..
        /// </summary>
        public static string MALFORMED_OR_EMPTY_PARAMETERS
        {
            get
            {
                return ResourceManager.GetString("MALFORMED_OR_EMPTY_PARAMETERS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string NOTIFICATIONTYPE_ACCOUNT
        {
            get
            {
                return ResourceManager.GetString("NOTIFICATIONTYPE_ACCOUNT", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Direct.
        /// </summary>
        public static string NOTIFICATIONTYPE_DIRECT
        {
            get
            {
                return ResourceManager.GetString("NOTIFICATIONTYPE_DIRECT", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Marketing.
        /// </summary>
        public static string NOTIFICATIONTYPE_MARKETING
        {
            get
            {
                return ResourceManager.GetString("NOTIFICATIONTYPE_MARKETING", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string NOTIFICATIONTYPE_TASKS
        {
            get
            {
                return ResourceManager.GetString("NOTIFICATIONTYPE_TASKS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Another user had already changed this same data so the operation could not be completed. Please try again with refreshed data..
        /// </summary>
        public static string OPTIMISTIC_CONCURRENCY_CONFLICT
        {
            get
            {
                return ResourceManager.GetString("OPTIMISTIC_CONCURRENCY_CONFLICT", resourceCulture);
            }
        }
    }
}